AWSTemplateFormatVersion: 2010-09-09
Description: This template creates an EFS File System with Mount Targets
Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: "VPC ID"
  SubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: "List of Subnet IDs for Mount Targets"
  EfsSecurityGroupId:
    Type: AWS::EC2::SecurityGroup::Id
    Description: "Security Group ID for EFS access from other services"

Resources:
  Efs:
    Type: AWS::EFS::FileSystem
    Properties:
      Encrypted: true
  EfsSecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: "EFS Security Group"
      VpcId: !Ref VpcId
  EfsSecurityGroupNFSinbound:
    Type: "AWS::EC2::SecurityGroupIngress"
    Properties:
      GroupId: !Ref EfsSecurityGroup
      IpProtocol: tcp
      FromPort: 2049
      ToPort: 2049
      SourceSecurityGroupId: !Ref EfsSecurityGroupId
  EfsMountTarget1:
        Type: AWS::EFS::MountTarget
        Properties:
            FileSystemId:
                Ref: Efs
            SubnetId: !Ref SubnetA
            SecurityGroups:
                - Ref: "EfsSecurityGroup"
  EfsMountTarget2:
        Type: AWS::EFS::MountTarget
        Properties:
            FileSystemId:
                Ref: Efs
            SubnetId: !Ref SubnetB
            SecurityGroups:
                - Ref: "EfsSecurityGroup"

Outputs:
  FileSystemId:
    Value: !Ref Efs
    Description: "EFS File System ID"
  SecurityGroupId:
    Value: !Ref EfsSecurityGroup
    Description: "EFS Security Group ID"